src/Entity/Enfant.php
<?php

namespace App\Entity;

use App\Repository\EnfantRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EnfantRepository::class)]
class Enfant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(name:"id_e")]
    private ?int $idE = null;

    #[ORM\Column(length: 55)]
    private ?string $Nom = null;

    #[ORM\Column(length: 25)]
    private ?string $Prenom = null;

    #[ORM\Column]
    private ?int $Age = null;

    #[ORM\Column(length: 255)]
    private ?string $Adresse = null;

    #[ORM\ManyToOne(inversedBy: 'enfants')]
    #[ORM\JoinColumn(nullable: true    )]
    private ?PersonneResponsable $personneResponsable = null;

    #[ORM\OneToOne(mappedBy: 'enfants', cascade: ['persist', 'remove'])]
    private ?DossierMedical $dossierMedical = null;

    #[ORM\OneToOne(mappedBy: 'enfants', cascade: ['persist', 'remove'])]
    private ?DossierScolaire $dossierScolaire = null;

    #[ORM\OneToOne(mappedBy: 'enfants', cascade: ['persist', 'remove'])]
    private ?DossierStage $dossierStage = null;

    #[ORM\ManyToOne(inversedBy: 'enfants')]
    #[ORM\JoinColumn(nullable: false)]
    private ?PersonneResponsable $idRP = null;

    #[ORM\ManyToOne(inversedBy: 'enfants')]
    #[ORM\JoinColumn(nullable: false)]
    private ?PersonneResponsable $personneresponsableid = null;

    #[ORM\ManyToOne(inversedBy: 'enfants')]
    private ?PersonneResponsable $idpersonneresponsable = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdE(): ?int
    {
        return $this->idE;
    }

    public function setIdE(int $idE): static
    {
        $this->idE = $idE;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): static
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): static
    {
        $this->Age = $Age;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): static
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getPersonneResponsable(): ?PersonneResponsable
    {
        return $this->personneResponsable;
    }

    public function setPersonneResponsable(?PersonneResponsable $personneResponsable): static
    {
        $this->personneResponsable = $personneResponsable;

        return $this;
    }

    public function getDossierMedical(): ?DossierMedical
    {
        return $this->dossierMedical;
    }

    public function setDossierMedical(DossierMedical $dossierMedical): static
    {
        // set the owning side of the relation if necessary
        if ($dossierMedical->getEnfants() !== $this) {
            $dossierMedical->setEnfants($this);
        }

        $this->dossierMedical = $dossierMedical;

        return $this;
    }

    public function getDossierScolaire(): ?DossierScolaire
    {
        return $this->dossierScolaire;
    }

    public function setDossierScolaire(DossierScolaire $dossierScolaire): static
    {
        // set the owning side of the relation if necessary
        if ($dossierScolaire->getEnfants() !== $this) {
            $dossierScolaire->setEnfants($this);
        }

        $this->dossierScolaire = $dossierScolaire;

        return $this;
    }

    public function getDossierStage(): ?DossierStage
    {
        return $this->dossierStage;
    }

    public function setDossierStage(?DossierStage $dossierStage): static
    {
        // unset the owning side of the relation if necessary
        if ($dossierStage === null && $this->dossierStage !== null) {
            $this->dossierStage->setEnfants(null);
        }

        // set the owning side of the relation if necessary
        if ($dossierStage !== null && $dossierStage->getEnfants() !== $this) {
            $dossierStage->setEnfants($this);
        }

        $this->dossierStage = $dossierStage;

        return $this;
    }

    public function getIdRP(): ?PersonneResponsable
    {
        return $this->idRP;
    }

    public function setIdRP(?PersonneResponsable $idRP): static
    {
        $this->idRP = $idRP;

        return $this;
    }

    public function getPersonneresponsableid(): ?PersonneResponsable
    {
        return $this->personneresponsableid;
    }

    public function setPersonneresponsableid(?PersonneResponsable $personneresponsableid): static
    {
        $this->personneresponsableid = $personneresponsableid;

        return $this;
    }

    public function getIdpersonneresponsable(): ?PersonneResponsable
    {
        return $this->idpersonneresponsable;
    }

    public function setIdpersonneresponsable(?PersonneResponsable $idpersonneresponsable): static
    {
        $this->idpersonneresponsable = $idpersonneresponsable;

        return $this;
    }
}

src/Entity/Famille.php
<?php

namespace App\Entity;

use App\Repository\FamilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FamilleRepository::class)]
class Famille
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(name: "id_e")]
    private ?int $idE = null;

    #[ORM\Column(length: 55)]
    private ?string $Nompere = null;

    #[ORM\Column(length: 25)]
    private ?string $Prenompere = null;

    #[ORM\Column(length: 55)]
    private ?string $Nommere = null;

    #[ORM\Column(length: 25)]
    private ?string $Prenommere = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Fratrie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $relation = null;

    #[ORM\ManyToMany(targetEntity: Enfant::class)]
    private Collection $enfants;

    public function __construct()
    {
        $this->enfants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdE(): ?int
    {
        return $this->idE;
    }

    public function setIdF(int $idE): static
    {
        $this->idE = $idE;

        return $this;
    }

    public function getNompere(): ?string
    {
        return $this->Nompere;
    }

    public function setNompere(string $Nompere): static
    {
        $this->Nompere = $Nompere;

        return $this;
    }

    public function getPrenompere(): ?string
    {
        return $this->Prenompere;
    }

    public function setPrenompere(string $Prenompere): static
    {
        $this->Prenompere = $Prenompere;

        return $this;
    }

    public function getNommere(): ?string
    {
        return $this->Nommere;
    }

    public function setNommere(string $Nommere): static
    {
        $this->Nommere = $Nommere;

        return $this;
    }

    public function getPrenommere(): ?string
    {
        return $this->Prenommere;
    }

    public function setPrenommere(string $Prenommere): static
    {
        $this->Prenommere = $Prenommere;

        return $this;
    }

    public function getFratrie(): ?string
    {
        return $this->Fratrie;
    }

    public function setFratrie(?string $Fratrie): static
    {
        $this->Fratrie = $Fratrie;

        return $this;
    }

    public function getRelation(): ?string
    {
        return $this->relation;
    }

    public function setRelation(?string $relation): static
    {
        $this->relation = $relation;

        return $this;
    }

    /**
     * @return Collection<int, Enfant>
     */
    public function getEnfants(): Collection
    {
        return $this->enfants;
    }

    public function addEnfant(Enfant $enfant): static
    {
        if (!$this->enfants->contains($enfant)) {
            $this->enfants->add($enfant);
        }

        return $this;
    }

    public function removeEnfant(Enfant $enfant): static
    {
        $this->enfants->removeElement($enfant);

        return $this;
    }
}

src/Controller/FamilleController.php
<?php

namespace App\Controller;

use App\Entity\Famille;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use  App\Repository\FamilleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FamilleController extends AbstractController


{
    #[Route('/famille/create', name:'app_famille_create')]
    public function create(Request $request, EntityManagerInterface $manager):Response
{
    $famille = new Famille();
    $form = $this->createFormBuilder($famille)
        ->add('idE')
        ->add('Nompere')
        ->add('Prenompere')
        ->add('Nommere')
        ->add('Prenommere')
        ->add('Fratrie')
        ->add('save', SubmitType::class,['label'=>'Enregistrer'])
        ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted()&&$form->isValid()){
            $manager->persist($famille);
            $manager->flush();

            return $this->redirectToRoute('app_famille_create');
            dump(famille);
        }
        return $this->render('famille/famille.index.html.twig',[
            'formFamille'=> $form->createView()
           
        ]);
        
    }

    #[Route('/formType/success', name: 'app_formType_success')]
    public function success(): Response
    
    {
        return $this->redirectToRoute('app_famille_create');
    
    }

    #[Route('/famille/edit/', name: 'app_famille_edit')]
     public function edit(Request $request, FamilleRepository $familleRepository)
      {
         $familles = $familleRepository->findAll(); // Récupère toutes les familles

 
       
        return $this->render('famille/famille.edit.html.twig', [
            'familles' => $familles, // Transmet toutes les familles à la vue
        ]);
        }
}
    

templates/famille/famille.edit.html.twig
{% block title %}<h1>Bienvenue sur la page de modification de mes formulaires!</h1>{% endblock %}
{% block body %}
<link rel="stylesheet" href="https://bootswatch.com/5/sketchy/bootstrap.min.css">
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                <a class="nav-link active" href="/enfant/create"><button type="button" class="btn btn-primary">Enfant</button>
                    <span class="visually-hidden">(current)</span>
                </a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/famille/create"> <button type="button" class="btn btn-warning"> Famille</button></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/personneresponsable/create"><button type="button" class="btn btn-success">Personne Responsable</button></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/dossiermedical/create"><button type="button" class="btn btn-info">Dossier Médical</button></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/dossierscolaire/create"><button type="button" class="btn btn-light">Dossier Scolaire</button></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href=" /dossierstage/create"><button type="button" class="btn btn-primary">Dossier Stage</button></a>
                </li>
 </nav>
            <h1> Modification d'un entité</h1>
             
                <h2>Liste des familles :</h2>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nom</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for famille in familles %}
            <tr>
                <td>{{ famille.idF }}</td>
                <td>{{ famille.nom }}</td>
                <td>{{ famille.description }}</td>
                <td>
                    <a href="{{ path('app_famille_edit', {'idF': famille.idF}) }}" class="btn btn-primary">Modifier</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/famille/famille.index.html.twig
{% block title %}<h1>Bienvenue sur la page de mes formulaires!!</h1> {% endblock %}


 {% block body %}
<link rel="stylesheet" href="https://bootswatch.com/5/sketchy/bootstrap.min.css">
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                <a class="nav-link active" href="/enfant/edit"><button type="button" class="btn btn-secondary">Enfant</button>
                    <span class="visually-hidden">(current)</span>
                </a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/famille/edit"> <button type="button" class="btn btn-warning"> Famille</button></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/personneresponsable/edit"><button type="button" class="btn btn-success">Personne Responsable</button></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/dossiermedical/edit"><button type="button" class="btn btn-info">Dossier Médical</button></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/dossierscolaire/edit"><button type="button" class="btn btn-light">Dossier Scolaire</button></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href=" /dossierstage/edit"><button type="button" class="btn btn-danger">Dossier Stage</button></a>
                </li>
            </ul>
                        
    </nav>

<h1>Création d'une entité</h1>

{{form_start(formFamille)}}
{{form_widget(formFamille)}}
{{form_end(formFamille)}}



 {% endblock %}